version: "2"
services:
  app:
    restart: always
    image: ghalibbajwa/slogr-agent:latest
    ports:
      - "5000:5000"
      
  server:
    restart: always
    image: ghalibbajwa/slogr-server:latest
    ports:
      - "8009:8009"
      - "60000:60000/udp"
    

 
